{
  "formatVersion": "1.1",
  "component": {
    "group": "com.satergo.jledger",
    "module": "transport-speculos",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.satergo.jledger",
          "module": "core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transport-speculos-0.0.1-SNAPSHOT.jar",
          "url": "transport-speculos-0.0.1-SNAPSHOT.jar",
          "size": 3131,
          "sha512": "b627a1a7b644a213fbe7b98d426a19e34fa2b0181e2d3fd01a9a6f08005dd12a3756f285990c3f5fb81be22c9b220ea2b4e60fe036944dc5b8e48c7477cab201",
          "sha256": "00769793114a781011d49fa50157cb481c231b6dc80c71afee087a81aaee3654",
          "sha1": "55aa2ecb3bba4ebe6f1c24ef4a14e0f834437f3a",
          "md5": "4e0088d68279e736adf36fa2c90a6980"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.satergo.jledger",
          "module": "core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transport-speculos-0.0.1-SNAPSHOT.jar",
          "url": "transport-speculos-0.0.1-SNAPSHOT.jar",
          "size": 3131,
          "sha512": "b627a1a7b644a213fbe7b98d426a19e34fa2b0181e2d3fd01a9a6f08005dd12a3756f285990c3f5fb81be22c9b220ea2b4e60fe036944dc5b8e48c7477cab201",
          "sha256": "00769793114a781011d49fa50157cb481c231b6dc80c71afee087a81aaee3654",
          "sha1": "55aa2ecb3bba4ebe6f1c24ef4a14e0f834437f3a",
          "md5": "4e0088d68279e736adf36fa2c90a6980"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transport-speculos-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "transport-speculos-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 96894,
          "sha512": "342f18b5a148ede9a0ee6a872c07043083fba521004f2e722458bcd3878e0a73db548c368c70b49573d14cf90d9811d1f9c108c0960040e4d83bfae3c1ff9273",
          "sha256": "0b994165fbc737f64c9f072f766f1abdfc33cb1fead917ce03db4826eeef80fe",
          "sha1": "03d9228c0fa5836a59c8bc3cdb36cc2efa34bd8c",
          "md5": "15055c12121d201131eed9e6b44a7405"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transport-speculos-0.0.1-SNAPSHOT-sources.jar",
          "url": "transport-speculos-0.0.1-SNAPSHOT-sources.jar",
          "size": 2080,
          "sha512": "cb10744abaeface6acdf049bc5ab545eb1b2a7973c7beb526cb53849e8a6fc52650274bb20718bbe99f52ea979947369caa2f4f9a7a95ef6927d8dc6a4d312c0",
          "sha256": "d48c8a5bcd644d8db423fb9543afb43f6b297f834a48a80c6cdbe6d44a8d60a2",
          "sha1": "bc217a75387e058bfc8c4adb5eba0b3bdf7aedfe",
          "md5": "ccd469b31999f497f7e1bf87c04b53be"
        }
      ]
    }
  ]
}
